services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: node_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: react_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    restart: always
volumes:
  mongo-data:
