services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: node_backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: react_frontend
    depends_on:
      - backend
    restart: always
  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    restart: always
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
